### ISSUE TITLE
Add more than 3 images

### ISSUE THREAD

**Issue by moh1122** [yoha/wlkthru#15]
Hello
Thank you for this great project,
can you please tell me how can I add more than 3 images.
I looked into the RootViewController.swift and added my images by code and I added them in assets but all i get are the images that are already there. 
Any help please?
Thank you

**Comment by yohannes** [comment]
You just have to add more images in the array and the image has to be in the acceptable format (*png / *jpg). Anyway, give me the committed link to your code & i'll take a look at it.

**Comment by moh1122** [comment]
i dont think so because i added the images in the correct format to the array but nothing is showing up

**Comment by yohannes** [comment]
Push your code to your repo n I'll take a look at it.

**Comment by moh1122** [comment]
//
//  ViewController.swift
//  Wlkthru
//
//  Created by Yohannes Wijaya on 7/22/16.
//  Copyright © 2016 Yohannes Wijaya. All rights reserved.
//

import UIKit

class RootViewController: UIViewController, UIPageViewControllerDataSource {

  // MARK: - Stored Properties

  enum SceneDescriptionFor {
    static let header = ["Capture Your Moment",
                              "Share Your Joy",
                              "Sync Your Life"]

```
static let subheader = ["Chat with live agents",
                             "Connect with them. Sharing is caring.",
                             "Synchronize your life data."]
```

  }

  let images = ["Photo1", "Photo2", "Photo3", "Photo4", "Photo5"]

  // MARK: - IBOutlet Properties

  @IBOutlet weak var headerLabel: UILabel!
  @IBOutlet weak var stackView: UIStackView!
  @IBOutlet weak var pageControl: UIPageControl!

  // MARK: - IBAction Methods

  @IBAction func registerButtonDidTouch(_ sender: UIButton) {

  }

  @IBAction func logInButtonDidTouch(_ sender: UIButton) {

  }

  // MARK: - UIPageViewControllerDataSource Methods

  func pageViewController(_ pageViewController: UIPageViewController, viewControllerBefore viewController: UIViewController) -> UIViewController? {
    guard let validPageContentViewController = viewController as? PageContentViewController else { return nil }
    var pageIndex = validPageContentViewController.pageIndex
    guard pageIndex > 0 else {
      self.pageControl.currentPage = 0
      return nil
    }
    self.pageControl.currentPage = pageIndex
    pageIndex = pageIndex - 1

```
return self.viewControllerAtIndex(pageIndex)
```

  }

  func pageViewController(_ pageViewController: UIPageViewController, viewControllerAfter viewController: UIViewController) -> UIViewController? {
    guard let validPageContentViewController = viewController as? PageContentViewController else { return nil }
    var pageIndex = validPageContentViewController.pageIndex
    guard pageIndex < SceneDescriptionFor.header.count - 1 else {
      self.pageControl.currentPage = SceneDescriptionFor.header.count - 1
      return nil
    }
    pageControl.currentPage = pageIndex
    pageIndex = pageIndex + 1

```
return self.viewControllerAtIndex(pageIndex)
```

  }

  // MARK: - UIViewController Methods

  override func viewDidLoad() {
    super.viewDidLoad()

```
guard let validStoryboard = self.storyboard, let validPageViewController = validStoryboard.instantiateViewController(withIdentifier: "PageViewController") as? UIPageViewController else { return }

validPageViewController.dataSource = self

guard let validPageContentViewController = self.viewControllerAtIndex(0) else { return }

validPageViewController.setViewControllers([validPageContentViewController], direction: UIPageViewControllerNavigationDirection.forward, animated: true, completion: nil)

validPageViewController.view.frame = CGRect(x: 0.0, y: 0.0, width: self.view.frame.size.width, height: self.view.frame.size.height)

self.addChildViewController(validPageViewController)
self.view.addSubview(validPageViewController.view)
validPageViewController.didMove(toParentViewController: self)
self.view.bringSubview(toFront: self.stackView)
self.view.bringSubview(toFront: self.headerLabel)
```

  }

  // MARK - Helper Methods

  fileprivate func viewControllerAtIndex(_ index: Int) -> PageContentViewController? {
    guard index != NSNotFound || (index >= 0 && index < SceneDescriptionFor.header.count) else { return nil }
    guard let validStoryboard = self.storyboard, let validPageContentViewController = validStoryboard.instantiateViewController(withIdentifier: "PageContentViewController") as? PageContentViewController else { return nil }

```
validPageContentViewController.pageIndex = index
validPageContentViewController.headerDescription = SceneDescriptionFor.header[index]
validPageContentViewController.subheaderDescription = SceneDescriptionFor.subheader[index]
validPageContentViewController.imageFile = self.images[index]

return validPageContentViewController
```

  }
}

**Comment by moh1122** [comment]
I only added the images in the array like tht 
let images = ["Photo1", "Photo2", "Photo3", "Photo4", "Photo5"]
but nothing appears

**Comment by yohannes** [comment]
the number of elements in the array header, subheader, and images must be the same.

**Comment by moh1122** [comment]
thnks its working now

**Comment by yohannes** [comment]
np
